version: '3'
services:
  app:
    build: .
    ports:
      - "7680:7680"
    env_file:
      - ./.env
    environment:
      - DATA_DIR=/data
      - LOGS_DIR=/logs
    volumes:
      - ./data:/data
      - ./logs:/logs